/**
 * KIVO PLATFORM SUBSCRIPTION PLANS & ENTITLEMENTS
 */

export const PLANS = {
  free: {
    id: 'free',
    name: 'Free Starter',
    badge: 'FREE',
    credits: 500,
    maxBots: 1,
    allowedProviders: ['groq'],
    allowWebsiteCrawling: false,
    maxKnowledgeItems: 3,
    priceNgn: 0,
    priceUsd: 0,
    description: 'Perfect for testing your first WhatsApp AI agent.',
    features: [
      '500 Monthly AI Credits',
      '1 Active WhatsApp Bot',
      'Groq Ultra-Fast AI Model',
      'Text & FAQ Knowledge Base',
      'Standard WhatsApp Simulator',
    ],
  },
  pro: {
    id: 'pro',
    name: 'Pro Agency',
    badge: 'POPULAR',
    credits: 15000,
    maxBots: 10,
    allowedProviders: ['groq', 'gemini', 'openrouter'],
    allowWebsiteCrawling: true,
    maxKnowledgeItems: 50,
    priceNgn: 45000,
    priceUsd: 35,
    description: 'For growing businesses, agencies, and online stores.',
    features: [
      '15,000 Monthly AI Credits',
      '10 Active WhatsApp Bots',
      'Claude 3.5, Gemini 2.0 & DeepSeek',
      'Automatic Website URL Crawler',
      'Human Handoff Team Inbox',
      'Product & Service Catalog Manager',
      'Advanced Automation Rules',
    ],
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise Scale',
    badge: 'UNLIMITED',
    credits: 100000,
    maxBots: 100,
    allowedProviders: ['groq', 'gemini', 'openrouter'],
    allowWebsiteCrawling: true,
    maxKnowledgeItems: 500,
    priceNgn: 180000,
    priceUsd: 140,
    description: 'For corporate organizations and high-volume brands.',
    features: [
      '100,000 Monthly AI Credits',
      'Unlimited WhatsApp Bots',
      'Dedicated Priority AI Gateway',
      'Custom API & Webhook Integrations',
      'Dedicated Account Manager',
      'SLA & 99.9% Uptime Guarantee',
    ],
  },
};